In [30]:
import numpy as np
import random as rnd

N = 5 #мерность матриц
TO_DIR = r''

def nice_m(m): #возвращает строку с массивом m без скобок и запятых
    s = ''
    for i in map(str, m):
        s += i + ';'
    return s

#возвращает массив из случайных чисел из n на n элементов
random_m = lambda n: ([rnd.randint(-333, 333) for i in range(n)] for i in range(n)) 

#возвращает списком столбец j матрицы m
mj_coloumn = lambda m, j: list(m[i][j] for i in range(N)) 

#возвращает сумму произведений двух массивов
m_sum = lambda m1, m2: sum(x * y for x, y in zip(m1, m2))

def save_to_f(f_name, m): #сохраняет матрицу в файл
    with open(TO_DIR + f_name +'.txt', 'w') as file:
        file.writelines((i + '\n') for i in map(nice_m, m))
        
def load_from_f(f_name, m): #загружает матрицу из файла
    m = []
    with open(TO_DIR + f_name +'.txt', 'r') as file:
        for j in range(N):
            m.append([int(i) for i in str(file.readline().rstrip('\n')).split(';')[:-1]])
            
class mas:
    def _init_(self, m1, m2): #объект из 2-х массивов
        self.m1 = []
        self.m2 = []
        self.m1m2 = []
    
    def m_random(self): #формирует матрицы случайных значений
        self.m1 = list(random_m(N))
        self.m2 = list(random_m(N))
        self.m1m2 = []

    def in_file(self, f_m1 = 'm1', f_m2 = 'm2'): #записывает массивы в файлы
        save_to_f(f_m1, self.m1)
        save_to_f(f_m2, self.m2)
                
    def from_file(self, f_m1 = 'm1', f_m2 = 'm2'): #получает значения массивов из файлов
        load_from_f(f_m1, self.m1)
        load_from_f(f_m2, self.m2)
    
    def m1_m2(self): #произведение матриц
        self.m1m2 = [[m_sum(self.m1[i], mj_coloumn(self.m2, j)) for j in range(N)] for i in range(N)]
    
    def m1m2_in_f(self, f_m1m2 = 'm1m2'): #записывает результат перемножения в файл
        save_to_f(f_m1m2, self.m1m2)
    
    def m1m2_from_f(self, f_m1m2 = 'm1m2'): #возвращает матрицу перемножения из файла
        load_from_f(f_m1m2, self.m1m2)
        
    def test(self):
        if (np.array(self.m1m2) == np.dot(np.array(self.m1), np.array(self.m2))).all():
            print('Numpy - OK')
        else:
            print('Numpy - ERROR')
        print(np.dot(np.array(self.m1), np.array(self.m2)))

In [31]:
#формирование матриц
obj = mas()
obj.m_random()
print('m1:')
print(obj.m1)
print('m2:')
print(obj.m2)

m1:
[[237, -79, 209, 233, 159], [-140, 135, 332, 235, 43], [-39, 157, 76, -190, -209], [26, 150, 41, -181, -249], [-162, 280, 292, 216, -225]]
m2:
[[-77, 239, -257, 136, -208], [-312, 165, -91, -228, -296], [212, 9, 234, 255, -263], [193, -230, -72, -142, 307], [191, -70, 32, 266, -216]]


In [32]:
#запись матриц в файл
obj.in_file()
#чтение из файла
obj.from_file()
print('m1:')
print(obj.m1)
print('m2:')
print(obj.m2)

m1:
[[237, -79, 209, 233, 159], [-140, 135, 332, 235, 43], [-39, 157, 76, -190, -209], [26, 150, 41, -181, -249], [-162, 280, 292, 216, -225]]
m2:
[[-77, 239, -257, 136, -208], [-312, 165, -91, -228, -296], [212, 9, 234, 255, -263], [193, -230, -72, -142, 307], [191, -70, 32, 266, -216]]


In [33]:
#перемножение матриц
obj.m1_m2()
print('m1 x m2:')
print(obj.m1m2)

m1 x m2:
[[126045, -19231, -16502, 112747, -43692], [92612, -65257, 85839, 12908, -35299], [-106458, 75598, 20512, -50334, -71534], [-122602, 90393, -5674, -60741, -62374], [-14269, -23820, 61730, -101934, -11068]]


In [34]:
#запись матрицы в файл
obj.m1m2_in_f()
#чтение из файла
obj.m1m2_from_f()
print('m1 x m2:')
print(obj.m1m2)

m1 x m2:
[[126045, -19231, -16502, 112747, -43692], [92612, -65257, 85839, 12908, -35299], [-106458, 75598, 20512, -50334, -71534], [-122602, 90393, -5674, -60741, -62374], [-14269, -23820, 61730, -101934, -11068]]


In [35]:
#сверка результата перемножения матриц с результатом Numpy
obj.test()

Numpy - OK
[[ 126045  -19231  -16502  112747  -43692]
 [  92612  -65257   85839   12908  -35299]
 [-106458   75598   20512  -50334  -71534]
 [-122602   90393   -5674  -60741  -62374]
 [ -14269  -23820   61730 -101934  -11068]]
