## Задание:
1. Создание 2-x массивов размерностью 5X5 из случайных чисел.
2. Запись этих массивов в разные файлы.
3. Чтение из файла записанных масивов и их перемножение.
4. Записи и чтения результата перемножения в файл.

In [45]:
from random import randint

class Matrix:
    
    def __init__(self, matrix):
        self.matrix = matrix

        
    @classmethod
    def random(cls, size):
        return cls([[randint(-100, 100) for i in range(size)] for j in range(size)])
    
        
    def print(self, end='\n'):
        for line in self.matrix:
            print('\t'.join(str(i) for i in line))
        print(end)
            
    
    def write_to_file(self, destination):
        with open(destination, 'w') as file:
            for line in self.matrix:
                file.write("\t".join(str(i) for i in line) + "\n")
                
            
    @classmethod
    def read_from_file(cls, source):
        with open(source, 'r') as file:
            lines = file.readlines()
        
        return cls([[int(value) for value in line.rstrip().split("\t")] for line in lines])
        
    
    def get_size(self, another_matrix):
        dimensions = (len(self.matrix), len(another_matrix)) \
            + tuple(map(len, self.matrix)) \
            + tuple(map(len, another_matrix))
        
        if min(dimensions) != max(dimensions):
            raise Exception('Matrix dimensions are not equel!')
            
        return min(dimensions)
    
    
    def multiply(self, another_matrix):
        try:
            size = self.get_size(another_matrix.matrix)
            return Matrix([[sum([self.matrix[k][i] * another_matrix.matrix[i][j] for i in range(size)]) for j in range(size)] for k in range(size)])
        except Exception as error:
            print(repr(error))
            


In [46]:
size = 5

A = Matrix.random(size)
B = Matrix.random(size)

A.write_to_file('A.txt')
B.write_to_file('B.txt')

A = Matrix.read_from_file('A.txt')
B = Matrix.read_from_file('B.txt')

C1 = A.multiply(B)
C2 = B.multiply(A)

C1.write_to_file('C1.txt')
C2.write_to_file('C2.txt')

C1 = Matrix.read_from_file('C1.txt')
C2 = Matrix.read_from_file('C2.txt')

C1.print()
C2.print()

2237	5908	-866	8176	-275
-8114	-4295	-6802	7515	-7727
179	-732	14659	-3007	-2519
5681	-11771	-7518	-9789	-6394
-9988	3822	5110	-4220	6970


-3401	7600	5637	-9250	-6045
-11766	17548	10026	-5429	-4283
10371	-4517	-2596	10428	3693
-17894	15169	-9296	-6864	4872
-10498	-503	-14277	-1303	5095




#### Проверка

In [47]:
from numpy import matmul

numpy_C1 = matmul(A.matrix, B.matrix)
numpy_C2 = matmul(B.matrix, A.matrix)

numpy_C1_list = list(list(line) for line in numpy_C1)
numpy_C2_list = list(list(line) for line in numpy_C2)

print('A * B:')
print('Our result:')
C1.print()

print('Numpy result:')
print(numpy_C1)

print('\nValid: ' + str(numpy_C1_list == C1.matrix))

print("\n" + '-'*100 + '\n')
print('B * A:')
print('Our result:')
C2.print()

print('Numpy result:')
print(numpy_C2)

print('\nValid: ' + str(numpy_C2_list == C2.matrix))

A * B:
Our result:
2237	5908	-866	8176	-275
-8114	-4295	-6802	7515	-7727
179	-732	14659	-3007	-2519
5681	-11771	-7518	-9789	-6394
-9988	3822	5110	-4220	6970


Numpy result:
[[  2237   5908   -866   8176   -275]
 [ -8114  -4295  -6802   7515  -7727]
 [   179   -732  14659  -3007  -2519]
 [  5681 -11771  -7518  -9789  -6394]
 [ -9988   3822   5110  -4220   6970]]

Valid: True

----------------------------------------------------------------------------------------------------

B * A:
Our result:
-3401	7600	5637	-9250	-6045
-11766	17548	10026	-5429	-4283
10371	-4517	-2596	10428	3693
-17894	15169	-9296	-6864	4872
-10498	-503	-14277	-1303	5095


Numpy result:
[[ -3401   7600   5637  -9250  -6045]
 [-11766  17548  10026  -5429  -4283]
 [ 10371  -4517  -2596  10428   3693]
 [-17894  15169  -9296  -6864   4872]
 [-10498   -503 -14277  -1303   5095]]

Valid: True
