## Hometask #1

In [1]:
import random

### Implementation of class

In [2]:
class RandomMatrix:
    def __init__(self, row_size, column_size):
        self._matrix = [[random.randint(0, 100) for _ in range(column_size)] for _ in range(row_size)]

    def save_to_file(self, file_name):
        with open(file_name, "w") as f:
            for row in self._matrix:
                for item in row:
                    f.write(f"{item} ")
                f.write("\n")

    def replace_matrix(self, matrix):
        self._matrix = matrix

    def get_matrix(self):
        return self._matrix

    @classmethod
    def create_from_file(cls, file_name):
        matrix = []
        with open(file_name) as f:
            for row in f:
                matrix.append([int(i) for i in row.strip("\n ").split(" ")])
        result = cls(0, 0)
        result._matrix = matrix
        return result

    def __getitem__(self, key):
        return self._matrix[key]

    def __len__(self):
        return len(self._matrix)

    @staticmethod
    def get_scalar_mul(vector1, vector2):
        return sum([vector1[i] * vector2[i] for i in range(len(vector1))])

    def __mul__(self, other):
        if isinstance(other, RandomMatrix):
            result = []
            for i in range(len(self)):
                row = []
                for j in range(len(other[0])):
                    row.append(self.get_scalar_mul(self[i], list(zip(*other))[j]))
                result.append(row)

            result_matrix = RandomMatrix(0, 0)
            result_matrix._matrix = result
            return result_matrix

        raise ValueError("Operand must be instance of RandomMatrix")

### Create matrices

In [3]:
matrix1 = RandomMatrix(5,5)
matrix2 = RandomMatrix(5,5)

### Save matrices to files

In [4]:
matrix1.save_to_file('m1.txt')
matrix2.save_to_file('m2.txt')

### Read matrices from file

In [5]:
matrix1_from_file = RandomMatrix.create_from_file('m1.txt')
matrix2_from_file = RandomMatrix.create_from_file('m2.txt')

### Multiplication of matrices

In [6]:
mul_matrix = matrix1_from_file * matrix2_from_file

###  Test

In [7]:
import numpy as np

In [8]:
np_matrix1 = np.array(matrix1_from_file.get_matrix())
np_matrix2 = np.array(matrix2_from_file.get_matrix())

mul_np_mtrix = np.matmul(np_matrix1, np_matrix2)

In [10]:
assert(np.array_equal(mul_matrix.get_matrix(), mul_np_mtrix))

In [12]:
print(mul_matrix.get_matrix())

[[17772, 11538, 11808, 9930, 10914], [22285, 9784, 7688, 10627, 20707], [25393, 18428, 11772, 10099, 19991], [25707, 17636, 14549, 12388, 19027], [23129, 16312, 10899, 10680, 18345]]


In [13]:
print(mul_np_mtrix)

[[17772 11538 11808  9930 10914]
 [22285  9784  7688 10627 20707]
 [25393 18428 11772 10099 19991]
 [25707 17636 14549 12388 19027]
 [23129 16312 10899 10680 18345]]
