#### Задание:
1. Создание 2-x массивов размерностью 5X5 из случайных чисел.
2. Запись этих массивов в разные файлы.
3. Чтение из файла записанных масивов и их перемножение.
4. Записи и чтения результата перемножения в файл.

In [1]:
import random
import numpy as np

In [2]:
class Matrix(object):
    
    def __init__(self, matrix=[], size=5):
        self.matr = matrix
        self.size = size
    
    def generate(self):
        self.matr = [[random.randint(-5, 5) for j in range(self.size)] for i in range(self.size)]
    
    def write_to_file(self, file_name):
        file = open(file_name, 'w')
        for i in range(self.size):
            for j in range(self.size):
                file.write(str(self.matr[i][j]) + "\n")
        file.close()
        
    def read_from_file(self, file_name):
        file = open(file_name, "r")
        self.matr = [[int(file.readline()) for j in range(self.size)] for i in range(self.size)]
        file.close()
        
    def multiply(self, matrix):
        temp = [[0 for j in range(self.size)] for i in range(self.size)]
        for i in range(self.size):
            for j in range(self.size):
                for k in range(self.size):
                    temp[i][j] += self.matr[i][k] * matrix.matr[k][j]
        return Matrix(temp)
        
    def multiply_with_numpy(self, matrix):
        temp = np.dot(self.matr, matrix.matr)
        return Matrix(temp) 
        
    def on_screen(self):
        print(np.array(self.matr))
        
    def is_equal(self, object1):
        if (self.matr == object1.matr).all():
            print("Matrices are equal.")
        else:
            print("Matrices are not equal.")

In [3]:
class Helper(object):
    
    def __init__(self):
        self.matrix1 = None
        self.matrix2 = None
        self.matrix3 = None
        self.matrix4 = None
        self.matrix5 = None
        self.matrix6 = None
        self.matrix7 = None
        
    def create(self):
        self.matrix1 = Matrix()
        self.matrix1.generate()
        self.matrix2 = Matrix()
        self.matrix2.generate()
        self.matrix3 = Matrix()
        self.matrix4 = Matrix()
        self.matrix5 = Matrix()
        self.matrix6 = Matrix()
        self.matrix7 = Matrix()

    def write_and_read(self):
        self.matrix1.write_to_file("Matrix_1.txt")
        self.matrix2.write_to_file("Matrix_2.txt")
        self.matrix3.read_from_file("Matrix_1.txt")
        self.matrix4.read_from_file("Matrix_2.txt")
        
    def multiplications(self):
        self.matrix5 = self.matrix3.multiply(self.matrix4)
        self.matrix6 = self.matrix3.multiply_with_numpy(self.matrix4)
        
    def show_on_screen(self):
        print("Ordinary multiplication:")
        self.matrix5.on_screen()
        print()
        print("Multiplication with numpy:")
        self.matrix6.on_screen()
        print()
        
    def check_answer(self):
        self.matrix5.is_equal(self.matrix6)
        print()
        
    def write_and_read_answer(self):
        self.matrix5.write_to_file("Answer.txt")
        self.matrix7.read_from_file("Answer.txt")
        
    def show_answer_on_screen(self):
        print("Answer:")
        self.matrix7.on_screen()

In [4]:
helper = Helper()
helper.create()
helper.write_and_read()
helper.multiplications()
helper.show_on_screen()
helper.check_answer()
helper.write_and_read_answer()
helper.show_answer_on_screen()

Ordinary multiplication:
[[  1 -36  17   1 -27]
 [  1 -12  13 -12  23]
 [  9  -2 -14   2 -18]
 [ 44 -19   4 -14 -43]
 [-23 -23  11  -5  10]]

Multiplication with numpy:
[[  1 -36  17   1 -27]
 [  1 -12  13 -12  23]
 [  9  -2 -14   2 -18]
 [ 44 -19   4 -14 -43]
 [-23 -23  11  -5  10]]

Matrices are equal.

Answer:
[[  1 -36  17   1 -27]
 [  1 -12  13 -12  23]
 [  9  -2 -14   2 -18]
 [ 44 -19   4 -14 -43]
 [-23 -23  11  -5  10]]
