Домашняя работа №1 Бондаренко Алексей

Класс:

In [56]:
import json
from random import randint

class Matrix:
    _matrix = []
    
    def __init__(self, matrix = []):
        '''default zero matrix'''
        if not matrix:
            matrix = [[[0] * 5] * 5]
        self._matrix = matrix
        
    def get(self):
        return self._matrix
        
    def generate(self):
        self._matrix = [[randint(0, 100) for i in range(5)] for i in range(5)]
        
    def load(self, file_path):
        with open(file_path, "r") as file_obj:
            self._matrix = json.loads(file_obj.read())
            
    def save(self, file_path):
        with open(file_path, "w") as file_obj:
            file_obj.write(json.dumps(self.get()))
    
    def getTansposed(self):
        return Matrix([[self._matrix[j][i] for j in range (0, 5)] for i in range(0, 5)])
        
    def multiply(self, second_matrix):
        if not isinstance(second_matrix, Matrix):
            raise Exception('matrix must be instance Matrix Class')
        multiply_rows = lambda row1, row2 : sum([row1[i] * row2[i] for i in range(0,5)])
        matrix1 = self.get()
        matrix2 = second_matrix.getTansposed().get()
        result = [[mult_rows(matrix1[i], matrix2[j]) for j in range(5)] for i in range(5)]
        return Matrix(result)
    

Проверка при помощи numpy и glob (сохранение)

In [58]:
import numpy as np
import glob

matrix1 = Matrix()
matrix2 = Matrix()
matrix1.generate()
matrix2.generate()

matrix1.save('matrix1.txt')
matrix2.save('matrix2.txt')

matrix1.load('matrix1.txt')
matrix2.load('matrix2.txt')

result_matrix = matrix1.multiply(matrix2)
result_matrix.save('result_matrix.txt')
result_matrix.load('result_matrix.txt')

print('All txt files in file directory:')
print(glob.glob("*.txt"))

print('Class result:')
print(np.array(result_matrix.get()))
print('Numpy result:')
print(np.matmul(matrix1.get(), matrix2.get()))
print('Сomparison:')
print(np.matmul(matrix1.get(), matrix2.get()) == np.array(result_matrix.get()))

All txt files in file directory:
['matrix1.txt', 'matrix2.txt', 'result_matrix.txt']
Class result:
[[11901 16617  8080  7088  9483]
 [ 9840 14440  8689  8442  9884]
 [13473 14203  9231  8368  8365]
 [10157 11314  5459  3890  5331]
 [17388 21430 12308 12116 12916]]
Numpy result:
[[11901 16617  8080  7088  9483]
 [ 9840 14440  8689  8442  9884]
 [13473 14203  9231  8368  8365]
 [10157 11314  5459  3890  5331]
 [17388 21430 12308 12116 12916]]
Сomparison:
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
