In [1]:
import random
import numpy as np

class ArrayHelper(object):
    def __init__(self):
        pass

    def generateNew(self, rowsCount, columnsCount):
        return [[random.randint(1,101) for j in range(columnsCount)] for i in range(rowsCount)]
    
    def writeToFile(self, path, arr): #serializes list
        with open(path, "w") as file_obj:
            file_obj.writelines(" ".join(map(str, row)) + '\n' for row in arr)

    def readFromFile(self, path): #returns deserialized list
        result = []
        with open(path, "r") as file_obj:
            data_list = file_obj.readlines()
            for line in data_list: 
                result.append([int(s) for s in line.rstrip('\n').split()])
        return result

    def multiply(self, a, b):
        rows = len(a)
        columns = len(a[0])

        product = [[0 for j in range(columns)] for i in range(rows)]

        for i in range(rows):
            for j in range(columns):
                for k in range(rows):
                    product[i][j] += a[i][k] * b[k][j]

        return product


helper = ArrayHelper()

a = helper.generateNew(5,5)
b = helper.generateNew(5,5)

helper.writeToFile('a', a)
helper.writeToFile('b', a)

aFromFile = helper.readFromFile('a')
bFromFile = helper.readFromFile('b')

print(np.matmul(aFromFile, bFromFile))
print(helper.multiply(aFromFile, bFromFile))

[[ 5278  6170  9673 10268  3869]
 [10411 10647 20117 21036 10138]
 [ 6725  3834 15310 13484  4256]
 [10122  9392 18399 19595  9516]
 [14230  8132 22415 23018 10051]]
[[5278, 6170, 9673, 10268, 3869], [10411, 10647, 20117, 21036, 10138], [6725, 3834, 15310, 13484, 4256], [10122, 9392, 18399, 19595, 9516], [14230, 8132, 22415, 23018, 10051]]
